[pytest]
filterwarnings =
    # Ignora solo las advertencias de deprecación
    ignore::DeprecationWarning
    # Ignora una advertencia específica que coincida con un texto usando regex
    ignore:.*Pydantic.*:UserWarning
    ignore:.*is experimental and may change or be removed.*